# ==========================
# Application
# ==========================
spring.application.name=transaccionesspinprueba

# ==========================
# PostgreSQL
# ==========================
spring.datasource.url=jdbc:postgresql://localhost:5432/spin_transactions
spring.datasource.username=${DB_USERNAME:spin_user}
spring.datasource.password=${DB_PASSWORD:spin_password}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================
# JPA / Hibernate
# ==========================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================
# Flyway
# ==========================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# ==========================
# Server
# ==========================
server.port=8080

# ========================
# OPEN FEIGN
# ========================
provider.transaction.url=${PROVIDER_TRANSACTION_URL:http://localhost:8080}
